### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by akkisagiraju**
Added my name at the end as a first time user.

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* WordPress version:
* PHP version:

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Remzi1993 — CHANGES_REQUESTED** [review]
Please add: Signed-off-by: Random J Developer <random@developer.example.org>
This is to ensure that you provided this code. This is also a good example for you, other projects do something similar. I need you only added your name, but this is an example how we would do this in a real-life scenario

**Review by akkisagiraju — COMMENTED** [review]
I'm adding Sign Off in my commit.

**Comment by Remzi1993** [comment]
I could also set it to pass for you, you're a first timer after all 😉
Do you want me to do this? Or do you want to try to change your commit message? Next time when you contribute you will need to do this.

**Comment by akkisagiraju** [comment]
> I could also set it to pass for you, you're a first timer after all 😉
> Do you want me to do this? Or do you want to try to change your commit message? Next time when you contribute you will need to do this.

Please do it for me. I'll do it myself the next time. :)

**Review by Remzi1993 — APPROVED** [review]

**Comment by akkisagiraju** [comment]
@Remzi1993 Do I have to use Git command line or the desktop app to merge a commit? Because the merge button was greyed out for me.

**Comment by Remzi1993** [comment]
@akkisagiraju The main branch (master) is by default protected, because this is our stable / production branch. If all the checks are green and someone has reviewed your code you will be able to merge it. Only an admin is able to ignore everything and (force) merge it. FOSSA was already green, only it is slow to give this information to GitHub so I merged it for you because you only added your name for the first timers example.

**Comment by akkisagiraju** [comment]
@Remzi1993 Got it. Thank you so much for letting me do this!

**Pull request merged**
